language:
  php

sudo: false

php:
  - 7.4
  - 8.0

install:
  - composer install

script:
  - ./comics test

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r .phpunit.cache/coverage-clover.xml