#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__.'/../../autoload.php';
}

try {
    $env = new \Symfony\Component\Dotenv\Dotenv(true);
    $env->load(__DIR__.'/.env');
} catch (\Exception $e) {
    echo $e->getMessage().PHP_EOL;
}

$commandClasses = [
    \Comics\Command\ComicCommand::class,
    \Comics\Command\TestCommand::class,
];

$statusCode = \Robo\Robo::run(
    $_SERVER['argv'],
    $commandClasses,
    'Comics to Webhooks',
    '2.0.0'
);

exit($statusCode);
