#!/usr/bin/env php
<?php
const APP_PATH = __DIR__;

$pharPath = \Phar::running(true);
if ($pharPath) {
    require_once "$pharPath/vendor/autoload.php";
} else {
    if (file_exists(__DIR__.'/vendor/autoload.php')) {
        require_once __DIR__.'/vendor/autoload.php';
    } elseif (file_exists(__DIR__.'/../../autoload.php')) {
        require_once __DIR__ . '/../../autoload.php';
    }
}

try {
    $env = new \Symfony\Component\Dotenv\Dotenv(APP_PATH);
    $env->load(APP_PATH . '/.env');
} catch (\Exception $e) {
    echo $e->getMessage(). PHP_EOL;
    exit();
}


$commandClasses = [
    \Comics\Commands\SendComicCommand::class,
];
$statusCode = \Robo\Robo::run(
    $_SERVER['argv'],
    $commandClasses,
    'Comics to Webhooks',
    '1.1.0'
);
exit($statusCode);